[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"
authors = ["Nayantha Yasiru nayanthayasiru@gmail.com | koraleg-se19014@stu.kln.ac.lk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
